<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout_navbar-toggler-icon</name>
   <tag></tag>
   <elementGuidId>9454bac3-59bc-44b3-ad00-19531fe9cdbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='title']/nav/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.navbar-toggler-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50f7fd79-f1c2-474d-9c12-27147e3405a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-toggler-icon</value>
      <webElementGuid>592cc816-65a3-430e-8963-3c3329b5d8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title&quot;)/nav[@class=&quot;navbar navbar-expand-lg bg&quot;]/div[@class=&quot;container-fluid&quot;]/button[@class=&quot;navbar-toggler&quot;]/span[@class=&quot;navbar-toggler-icon&quot;]</value>
      <webElementGuid>b771ebcd-d46c-4ae9-b4cd-bcd183bafe13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='title']/nav/div/button/span</value>
      <webElementGuid>74946c5e-5ad1-433e-a48b-761a0bad3532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>ab7241fc-00b1-475d-8a12-a12cb3f77470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
