<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buy</name>
   <tag></tag>
   <elementGuidId>0c085a94-c1a4-4355-9ab0-372212bf5a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='other']/button)[18]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5483d73a-9aa0-4551-bae9-7a13f7cf2544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn add-cart</value>
      <webElementGuid>a0a1782f-239a-4393-ae23-332062150d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>659ccb8d-cb14-40ff-a619-28532cd9c5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy</value>
      <webElementGuid>ede0068b-8008-410d-ad89-676a42be72ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-menu&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card-product-box&quot;]/div[@id=&quot;other&quot;]/button[@class=&quot;btn add-cart&quot;]</value>
      <webElementGuid>8b4af2bb-ea36-48c1-9597-5b6b1ee6c491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='other']/button)[18]</value>
      <webElementGuid>26d831bc-9af6-49cf-bb42-a625e42a6754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2'])[4]/following::button[1]</value>
      <webElementGuid>984f1cd6-b4c6-4123-9e27-90429c2924cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Japanese beer'])[1]/following::button[1]</value>
      <webElementGuid>3d581996-ded6-43f4-9563-cd5cb8c9c560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Water'])[1]/preceding::button[1]</value>
      <webElementGuid>bc971597-3c53-45af-9043-063acd5ddfa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AngKaew'])[1]/preceding::button[1]</value>
      <webElementGuid>01399dc0-bc7b-4cbf-84ae-1e79350d1c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/button</value>
      <webElementGuid>543ea41d-6a6a-4e87-8313-b0b493a7f732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Buy' or . = 'Buy')]</value>
      <webElementGuid>fbf92302-0e72-4b18-a8ac-5114cbbb5c9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
