<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Name_form9Example2</name>
   <tag></tag>
   <elementGuidId>11451bc8-03ef-4e0e-9fe3-ac8564f2dbbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form9Example2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form9Example2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58bd8cea-1bbe-4506-860c-1461193d37f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7d5859d-ad9c-4666-8fbf-7d8d7f9451c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form9Example2</value>
      <webElementGuid>28fed7ba-058e-4378-b7ce-1b11b2ae870b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-custom</value>
      <webElementGuid>aef8f2d5-621a-4c1a-80b8-a0c59cf65c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form9Example2&quot;)</value>
      <webElementGuid>523bf5b4-f939-4178-a381-21f7a728f20d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form9Example2']</value>
      <webElementGuid>e9477605-1bdf-4078-bee9-522c5bd6f7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box']/div/div/form/div/div[2]/div/input</value>
      <webElementGuid>a1b2c4e7-aac3-4f60-8ba9-e792485132c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b1e05ab0-1bfd-424f-9dcc-13f3adf8d56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'form9Example2']</value>
      <webElementGuid>f66d43cf-58cf-4f90-9a5b-7127cdab4e32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
