<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login_navbar-toggler-icon</name>
   <tag></tag>
   <elementGuidId>bff0912b-8d1c-44f6-a2b7-b44a0087d5f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='title']/nav/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.navbar-toggler-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0588889e-66a9-4ff3-9e6a-c72735f9b015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-toggler-icon</value>
      <webElementGuid>964323af-f0c9-424e-a9b2-7c88ef2b4ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title&quot;)/nav[@class=&quot;navbar navbar-expand-lg bg&quot;]/div[@class=&quot;container-fluid&quot;]/button[@class=&quot;navbar-toggler&quot;]/span[@class=&quot;navbar-toggler-icon&quot;]</value>
      <webElementGuid>7b014999-06b1-4feb-a30f-b3d4da4d31d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='title']/nav/div/button/span</value>
      <webElementGuid>cdd7ade1-c3b5-4f4f-a0a2-9f6342258441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>e7a9bff7-61ac-447b-bf55-83b4b076ebef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
