<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>fc6fcb5d-fd9c-4d7f-bdf6-53776bdd47c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Register')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3862055b-cbd7-4d22-a4c1-236ee16a3825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/register</value>
      <webElementGuid>935eebfd-2cd1-4c9d-8522-8e51072e5ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>5c63303a-a016-4271-92d9-0d24b4d89d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/section[1]/div[@class=&quot;form-box&quot;]/div[@class=&quot;form-value&quot;]/form[2]/div[@class=&quot;register&quot;]/p[1]/a[1]</value>
      <webElementGuid>ed3851e0-0714-4651-9f95-0ce0124c1285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>21b0dd1f-46d2-4acd-9791-58e899a08736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::a[1]</value>
      <webElementGuid>68226000-99d2-4b18-9092-4469d1372c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN'])[1]/following::a[1]</value>
      <webElementGuid>918694b2-3b52-4b7c-bb1f-fa1b407fe64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login as Admin'])[1]/preceding::a[1]</value>
      <webElementGuid>459e7631-cae9-422c-a8ba-9b6d87f663b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>537adf5c-34d0-4e48-b660-6bc2a6e6be6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/register')]</value>
      <webElementGuid>7546c068-daa0-4230-b245-0fa27b8c21ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>184ef17d-3b60-46d2-8392-3753f4b42290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/register' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>7b471642-3dce-4a18-bb75-63f271ec39ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
