<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Tracking Orders</name>
   <tag></tag>
   <elementGuidId>06db62a5-bc68-43cf-a7f6-0c6d412292ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cooking'])[1]/preceding::header[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>header.card-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>6a0b4e67-87d6-4d40-bff3-b9be06477621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>8c2486c7-b803-4751-8f0c-935f8861a1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tracking Orders </value>
      <webElementGuid>b5a76141-236a-4231-8b87-9fbe5af6c272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/header[@class=&quot;card-header&quot;]</value>
      <webElementGuid>f9cc4955-c9ea-4c67-81e7-6e47b0959a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cooking'])[1]/preceding::header[1]</value>
      <webElementGuid>a93ae502-7974-4ece-bf0e-42a01690a9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tracking Orders']/parent::*</value>
      <webElementGuid>2fa227a1-3a88-4ba7-8612-fd5445e94f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>bf0377f4-064e-4102-ba80-616ee16b1ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = ' Tracking Orders ' or . = ' Tracking Orders ')]</value>
      <webElementGuid>f6810a67-f8ce-474b-b828-2e5a80c346a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
