<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REGISTER_userEmail</name>
   <tag></tag>
   <elementGuidId>5d9ce468-d898-4642-ad26-dbe811572a09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='userEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;userEmail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff4adf86-c58e-4a4d-b418-c4bd392d88e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>1b7246a9-ecda-4e72-9a5c-4569a42d801e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>ab925dff-5170-4b76-b4ee-76ac7f173833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userEmail</value>
      <webElementGuid>30148076-8e24-4bf0-a23f-d92dc92abd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/section[1]/div[@class=&quot;form-box&quot;]/div[@class=&quot;form-value&quot;]/form[1]/div[@class=&quot;inputbox&quot;]/input[1]</value>
      <webElementGuid>08362a1f-5ec7-4070-baf8-aa51f6c4048d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='userEmail']</value>
      <webElementGuid>cc7de8eb-fab6-4e24-9db2-3ac1b1608f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c4f67adf-f16d-4f38-ba4a-e7da4b1374dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Email' and @name = 'userEmail']</value>
      <webElementGuid>01bde776-0c75-46f5-949b-212528c9b240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
